# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{virtualmonkey}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Deininger"]
  s.date = %q{2011-01-07}
  s.description = %q{monkey see, monkey do, monkey repeat}
  s.email = %q{jeremy@rightscale.com}
  s.executables = ["vary_instance_types", "grinder", "mcicp", "monkey"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/grinder",
    "bin/mcicp",
    "bin/monkey",
    "bin/vary_instance_types",
    "config/cloud_variables/all_clouds.json",
    "config/cloud_variables/east.json",
    "config/cloud_variables/rackspace.json",
    "config/cloud_variables/west.json",
    "config/common_inputs/apache_haproxy.json",
    "config/common_inputs/base.json",
    "config/common_inputs/ebs_toolbox.json",
    "config/common_inputs/haproxy.json",
    "config/common_inputs/lamp.json",
    "config/common_inputs/mysql.json",
    "config/common_inputs/none.json",
    "config/common_inputs/php.json",
    "config/common_inputs/php_aio_trial_chef_alpha.json",
    "config/common_inputs/php_app_fe_chef.json",
    "config/common_inputs/php_elb.json",
    "config/common_inputs/qstart.json",
    "config/common_inputs/rails.json",
    "config/common_inputs/rails_aio_demo_chef_alpha.json",
    "config/common_inputs/rails_aio_developer_chef_alpha.json",
    "config/common_inputs/rsgrid.json",
    "config/common_inputs/tomcat.json",
    "config/common_inputs/windows_blog_engine.json",
    "config/common_inputs/windows_net_aio.json",
    "config/troop/11H1/backup/base.json",
    "config/troop/11H1/backup/lamp_mysql_50.json",
    "config/troop/11H1/backup/lamp_mysql_51.json",
    "config/troop/11H1/backup/loadbalancer-php.json",
    "config/troop/11H1/backup/loadbalancer.json",
    "config/troop/11H1/backup/loadbalancer_rails.json",
    "config/troop/11H1/backup/loadbalancer_tomcat6.json",
    "config/troop/11H1/backup/mysql50.json",
    "config/troop/11H1/backup/mysql50_toolbox.json",
    "config/troop/11H1/backup/mysql51.json",
    "config/troop/11H1/backup/mysql51_toolbox.json",
    "config/troop/11H1/backup/php_elb.json",
    "config/troop/11H1/base.json",
    "config/troop/11H1/ebs_toolbox.json",
    "config/troop/11H1/lamp_mysql_50.json",
    "config/troop/11H1/lamp_mysql_51.json",
    "config/troop/11H1/loadbalancer-php.json",
    "config/troop/11H1/loadbalancer.json",
    "config/troop/11H1/loadbalancer_rails.json",
    "config/troop/11H1/loadbalancer_tomcat6.json",
    "config/troop/11H1/mysql50.json",
    "config/troop/11H1/mysql50_toolbox.json",
    "config/troop/11H1/mysql51.json",
    "config/troop/11H1/mysql51_awsdns.json",
    "config/troop/11H1/mysql51_debug.json",
    "config/troop/11H1/mysql51_toolbox.json",
    "config/troop/11H1/php.json",
    "config/troop/11H1/php_elb.json",
    "config/troop/11H1/rails.json",
    "config/troop/11H1/tomcat6.json",
    "config/troop/chef_quickstart.json",
    "config/troop/just_elb",
    "config/troop/lamp_v4.json",
    "config/troop/patch_test.json",
    "config/troop/rightlink.json",
    "config/troop/simple_fail.json",
    "config/troop/simple_pass.json",
    "config/troop/windows_blog_engine.json",
    "config/troop/windows_net_aio.json",
    "config/troop/windows_quick_start.json",
    "features/base.rb",
    "features/db_toolbox.rb",
    "features/ebs_toolbox.rb",
    "features/lamp.rb",
    "features/lb-apache-haproxy.rb",
    "features/mysql_5.x_v2_v4_from_scratch.rb",
    "features/mysql_5.x_v2_v4_from_scratch_awsdns.rb",
    "features/mysql_5.x_v2_v4_from_scratch_dyndns.rb",
    "features/mysql_v1_upgrade_v2.rb",
    "features/old_cuke_features/Rakefile",
    "features/old_cuke_features/Steps-TODO",
    "features/old_cuke_features/app_state.feature",
    "features/old_cuke_features/app_test.feature",
    "features/old_cuke_features/base.feature",
    "features/old_cuke_features/chef_quickstart.feature",
    "features/old_cuke_features/db_toolbox.feature",
    "features/old_cuke_features/ebs_toolbox.feature",
    "features/old_cuke_features/elb_create_delete.feature",
    "features/old_cuke_features/elb_generic.feature",
    "features/old_cuke_features/fe_app_checks.feature",
    "features/old_cuke_features/just-start.feature",
    "features/old_cuke_features/lamp.feature",
    "features/old_cuke_features/lb-apache-haproxy.feature",
    "features/old_cuke_features/mysql_5.x_v2_v4_from_scratch.feature",
    "features/old_cuke_features/mysql_5.x_v2_v4_from_scratch_awsdns.feature",
    "features/old_cuke_features/mysql_5.x_v2_v4_from_scratch_dyndns.feature",
    "features/old_cuke_features/mysql_chef_premium.feature",
    "features/old_cuke_features/mysql_chef_premium_from_scratch.feature",
    "features/old_cuke_features/mysql_v1_upgrade_v2.feature",
    "features/old_cuke_features/php.feature",
    "features/old_cuke_features/php_aio_trial_chef_alpha.feature",
    "features/old_cuke_features/php_chef.feature",
    "features/old_cuke_features/php_elb.feature",
    "features/old_cuke_features/rails.feature",
    "features/old_cuke_features/rails_aio_developer_chef.feature",
    "features/old_cuke_features/reboot.feature",
    "features/old_cuke_features/rightlink.feature",
    "features/old_cuke_features/rsgrid.feature",
    "features/old_cuke_features/simple.feature",
    "features/old_cuke_features/simple_fail.feature",
    "features/old_cuke_features/start-stop.feature",
    "features/old_cuke_features/step_definitions/app.rb",
    "features/old_cuke_features/step_definitions/deployment_steps.rb",
    "features/old_cuke_features/step_definitions/ebs.rb",
    "features/old_cuke_features/step_definitions/elb.rb",
    "features/old_cuke_features/step_definitions/lb.rb",
    "features/old_cuke_features/step_definitions/mysql_steps.rb",
    "features/old_cuke_features/terminate.feature",
    "features/old_cuke_features/tomcat6-tests-TODO",
    "features/old_cuke_features/tomcat6.feature",
    "features/patch_test.rb",
    "features/php.rb",
    "features/php_elb.rb",
    "features/rails.rb",
    "features/start_only.rb",
    "features/tomcat6.rb",
    "lib/virtualmonkey.rb",
    "lib/virtualmonkey/application.rb",
    "lib/virtualmonkey/application_frontend.rb",
    "lib/virtualmonkey/command.rb",
    "lib/virtualmonkey/command/clone.rb",
    "lib/virtualmonkey/command/create.rb",
    "lib/virtualmonkey/command/destroy.rb",
    "lib/virtualmonkey/command/list.rb",
    "lib/virtualmonkey/command/run.rb",
    "lib/virtualmonkey/command/troop.rb",
    "lib/virtualmonkey/cuke_monk.rb",
    "lib/virtualmonkey/deployment_monk.rb",
    "lib/virtualmonkey/deployment_runner.rb",
    "lib/virtualmonkey/ebs.rb",
    "lib/virtualmonkey/ebs_runner.rb",
    "lib/virtualmonkey/elb_runner.rb",
    "lib/virtualmonkey/fe_app_runner.rb",
    "lib/virtualmonkey/file_locations.rb",
    "lib/virtualmonkey/frontend.rb",
    "lib/virtualmonkey/http_checks.rb",
    "lib/virtualmonkey/index.html.erb",
    "lib/virtualmonkey/lamp_runner.rb",
    "lib/virtualmonkey/mysql.rb",
    "lib/virtualmonkey/mysql_runner.rb",
    "lib/virtualmonkey/mysql_toolbox_runner.rb",
    "lib/virtualmonkey/patch_runner.rb",
    "lib/virtualmonkey/php_aio_trial_chef_runner.rb",
    "lib/virtualmonkey/php_chef_runner.rb",
    "lib/virtualmonkey/rails_aio_developer_chef_runner.rb",
    "lib/virtualmonkey/shared_dns.rb",
    "lib/virtualmonkey/simple.rb",
    "lib/virtualmonkey/simple_runner.rb",
    "lib/virtualmonkey/test_case_interface.rb",
    "lib/virtualmonkey/unified_application.rb",
    "spec/bug3518.rb",
    "spec/concurrent_writes_spec.rb",
    "spec/cuke_job_spec.rb",
    "spec/ek.rb",
    "spec/little_ruby.rb",
    "spec/mini.rb",
    "spec/monitoring.rb",
    "spec/release_aws_dns.rb",
    "spec/release_dns.rb",
    "spec/release_dyndns.rb",
    "spec/shared_resources_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/virtualmonkey_spec.rb",
    "virtualmonkey.gemspec"
  ]
  s.homepage = %q{http://github.com/jeremyd/virtualmonkey}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{testing cluster deployments}
  s.test_files = [
    "spec/bug3518.rb",
    "spec/concurrent_writes_spec.rb",
    "spec/cuke_job_spec.rb",
    "spec/ek.rb",
    "spec/little_ruby.rb",
    "spec/mini.rb",
    "spec/monitoring.rb",
    "spec/release_aws_dns.rb",
    "spec/release_dns.rb",
    "spec/release_dyndns.rb",
    "spec/shared_resources_spec.rb",
    "spec/spec_helper.rb",
    "spec/virtualmonkey_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemedit>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_runtime_dependency(%q<rest_connection>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<right_popen>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemedit>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<rest_connection>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<right_popen>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemedit>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<rest_connection>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<right_popen>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

