# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{virtualmonkey}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Deininger"]
  s.date = %q{2010-11-16}
  s.description = %q{monkey see, monkey do, monkey repeat}
  s.email = %q{jeremy@rightscale.com}
  s.executables = ["monkey", "mcicp"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/mcicp",
     "bin/monkey",
     "config/cloud_variables/all_clouds.json",
     "config/cloud_variables/east.json",
     "config/cloud_variables/rackspace.json",
     "config/cloud_variables/west.json",
     "config/common_inputs/apache_haproxy.json",
     "config/common_inputs/ebs_toolbox.json",
     "config/common_inputs/haproxy.json",
     "config/common_inputs/lamp.json",
     "config/common_inputs/mysql.json",
     "config/common_inputs/none.json",
     "config/common_inputs/php.json",
     "config/common_inputs/php_aio_trial_chef_alpha.json",
     "config/common_inputs/php_app_fe_chef.json",
     "config/common_inputs/php_elb.json",
     "config/common_inputs/qstart.json",
     "config/common_inputs/rails.json",
     "config/common_inputs/rails_aio_demo_chef_alpha.json",
     "config/common_inputs/rails_aio_developer_chef_alpha.json",
     "config/common_inputs/rsgrid.json",
     "config/common_inputs/tomcat.json",
     "config/troop/apache_haproxy_10_sprint21.json",
     "config/troop/chef_quickstart.json",
     "config/troop/lamp.json",
     "config/troop/lamp_v5.json",
     "config/troop/mysql51.json",
     "config/troop/mysql51_sprint21.json",
     "config/troop/mysqlv2.json",
     "config/troop/php.json",
     "config/troop/php_elb.json",
     "config/troop/php_half_cloud.json",
     "config/troop/rails.json",
     "config/troop/rightlink.json",
     "config/troop/simple_fail.json",
     "config/troop/simple_pass.json",
     "config/troop/tomcat6_sprint21.json",
     "features/Rakefile",
     "features/Steps-TODO",
     "features/app_state.feature",
     "features/app_test.feature",
     "features/chef_quickstart.feature",
     "features/db_toolbox.feature",
     "features/ebs_toolbox.feature",
     "features/elb_create_delete.feature",
     "features/fe_app_checks.feature",
     "features/just_elb",
     "features/lamp.feature",
     "features/lb-apache-haproxy.feature",
     "features/mysql_5.x_v2_v4_from_scratch.feature",
     "features/mysql_5.x_v2_v4_from_scratch_dyndns.feature",
     "features/mysql_chef_premium.feature",
     "features/mysql_chef_premium_from_scratch.feature",
     "features/mysql_v1_upgrade_v2.feature",
     "features/php.feature",
     "features/php_aio_trial_chef_alpha.feature",
     "features/php_chef.feature",
     "features/php_elb.feature",
     "features/qstart.feature",
     "features/rails.feature",
     "features/rails_aio_developer_chef.feature",
     "features/reboot.feature",
     "features/rightlink.feature",
     "features/rsgrid.feature",
     "features/simple.feature",
     "features/simple_fail.feature",
     "features/step_definitions/app.rb",
     "features/step_definitions/deployment_steps.rb",
     "features/step_definitions/ebs.rb",
     "features/step_definitions/elb.rb",
     "features/step_definitions/lb.rb",
     "features/step_definitions/mysql_steps.rb",
     "features/terminate.feature",
     "features/tomcat6-tests-TODO",
     "features/tomcat6.feature",
     "lib/virtualmonkey.rb",
     "lib/virtualmonkey/application.rb",
     "lib/virtualmonkey/application_frontend.rb",
     "lib/virtualmonkey/command.rb",
     "lib/virtualmonkey/command/create.rb",
     "lib/virtualmonkey/command/destroy.rb",
     "lib/virtualmonkey/command/list.rb",
     "lib/virtualmonkey/command/run.rb",
     "lib/virtualmonkey/command/troop.rb",
     "lib/virtualmonkey/cuke_monk.rb",
     "lib/virtualmonkey/deployment_monk.rb",
     "lib/virtualmonkey/deployment_runner.rb",
     "lib/virtualmonkey/ebs.rb",
     "lib/virtualmonkey/ebs_runner.rb",
     "lib/virtualmonkey/elb_runner.rb",
     "lib/virtualmonkey/fe_app_runner.rb",
     "lib/virtualmonkey/file_locations.rb",
     "lib/virtualmonkey/frontend.rb",
     "lib/virtualmonkey/http_checks.rb",
     "lib/virtualmonkey/index.html.erb",
     "lib/virtualmonkey/lamp_runner.rb",
     "lib/virtualmonkey/mysql.rb",
     "lib/virtualmonkey/mysql_runner.rb",
     "lib/virtualmonkey/mysql_toolbox_runner.rb",
     "lib/virtualmonkey/php_aio_trial_chef_runner.rb",
     "lib/virtualmonkey/php_chef_runner.rb",
     "lib/virtualmonkey/rails_aio_developer_chef_runner.rb",
     "lib/virtualmonkey/shared_dns.rb",
     "lib/virtualmonkey/simple_runner.rb",
     "lib/virtualmonkey/unified_application.rb",
     "spec/bug3518.rb",
     "spec/concurrent_writes_spec.rb",
     "spec/cuke_job_spec.rb",
     "spec/ek.rb",
     "spec/mini.rb",
     "spec/release_dns.rb",
     "spec/shared_resources_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/virtualmonkey_spec.rb",
     "virtualmonkey.gemspec"
  ]
  s.homepage = %q{http://github.com/jeremyd/virtualmonkey}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{testing cluster deployments}
  s.test_files = [
    "spec/cuke_job_spec.rb",
     "spec/ek.rb",
     "spec/mini.rb",
     "spec/shared_resources_spec.rb",
     "spec/spec_helper.rb",
     "spec/bug3518.rb",
     "spec/concurrent_writes_spec.rb",
     "spec/virtualmonkey_spec.rb",
     "spec/release_dns.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_runtime_dependency(%q<rest_connection>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<gherkin>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<uuidtools>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<right_popen>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<rest_connection>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<gherkin>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<uuidtools>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<right_popen>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<rest_connection>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<gherkin>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<uuidtools>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<right_popen>, [">= 0"])
  end
end

